// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_characters2 from "./routes/(platform)/characters2.tsx";
import * as $_platform_favorites from "./routes/(platform)/favorites.tsx";
import * as $_platform_search from "./routes/(platform)/search.tsx";
import * as $_platform_staff from "./routes/(platform)/staff.tsx";
import * as $_platform_staff2 from "./routes/(platform)/staff2.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $characters_id_ from "./routes/characters/[id].tsx";
import * as $houses_house_ from "./routes/houses/[house].tsx";
import * as $index from "./routes/index.tsx";
import * as $logout from "./routes/logout.ts";
import * as $CharacterListIsla from "./islands/CharacterListIsla.tsx";
import * as $FavoriteButton from "./islands/FavoriteButton.tsx";
import * as $FavoritesList from "./islands/FavoritesList.tsx";
import * as $FilteredCharacterList from "./islands/FilteredCharacterList.tsx";
import * as $PaginatedCharacters from "./islands/PaginatedCharacters.tsx";
import * as $Pagination from "./islands/Pagination.tsx";
import * as $PaginationControlsla from "./islands/PaginationControlsla.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $SearchBarIsla from "./islands/SearchBarIsla.tsx";
import * as $StaffListIsla from "./islands/StaffListIsla.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/characters2.tsx": $_platform_characters2,
    "./routes/(platform)/favorites.tsx": $_platform_favorites,
    "./routes/(platform)/search.tsx": $_platform_search,
    "./routes/(platform)/staff.tsx": $_platform_staff,
    "./routes/(platform)/staff2.tsx": $_platform_staff2,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/characters/[id].tsx": $characters_id_,
    "./routes/houses/[house].tsx": $houses_house_,
    "./routes/index.tsx": $index,
    "./routes/logout.ts": $logout,
  },
  islands: {
    "./islands/CharacterListIsla.tsx": $CharacterListIsla,
    "./islands/FavoriteButton.tsx": $FavoriteButton,
    "./islands/FavoritesList.tsx": $FavoritesList,
    "./islands/FilteredCharacterList.tsx": $FilteredCharacterList,
    "./islands/PaginatedCharacters.tsx": $PaginatedCharacters,
    "./islands/Pagination.tsx": $Pagination,
    "./islands/PaginationControlsla.tsx": $PaginationControlsla,
    "./islands/Search.tsx": $Search,
    "./islands/SearchBarIsla.tsx": $SearchBarIsla,
    "./islands/StaffListIsla.tsx": $StaffListIsla,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
